name: deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 🚀 Build & Deploy darbud-wp-theme
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build (production)
        run: npm run build:prod

      - name: 📤 FTP Deploy (FTPS strict)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: strict
          server-dir: /darbud/wp-content/themes/darbud-wp-theme/
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/src/**
            **/.env*
            **/*.map
            package.json
            package-lock.json
            postcss.config.js
            prettier.config.js
            webpack.config.js
            README.md
